version: 2.1
orbs:
  node: circleci/node@4.1.0

workflows:
  angular-tests:
    jobs:
      - angular-test:
          pre-steps:
            - run:
                command: export NG_CLI_ANALYTICS=ci && sudo  -E npm install -g @angular/cli  &&  sudo  -E npm install --save-dev @angular-devkit/build-angular
jobs:

  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
    #  - checkout
    #  - node/install-packages
      - run:
          command:  cd ./angular-nini  && npm run test

  angular-test:
    executor:
      name: node/default
      tag: '13.14'
    
    steps:
    
      - run:
          command: ls
      - run:
          command: cd ./angular-nini  && npm run test
