version: 2.1
orbs:
  node: circleci/node@4.1.0

workflows:
  angular-tests:
    jobs:
      - angular-test
jobs:
  angular-test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
        app-dir: ./angular-nini
      - run:
          app-dir: ./angular-nini
          command: npm run test
