version: 2.1
orbs:
  node: circleci/node@4.1.0

workflows:
  angular-tests:
    jobs:
      - test
jobs:

  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command:  cd ./angular-nini  && npm run test

  angular-test:
    executor:
      name: node/default
      tag: '13.14'
    
    steps:
      - checkout
      - run:
          command: cd ./angular-nini  && npm run test
