version: 2.1
orbs:
  node: circleci/node@4.1.0

workflows:
  angular-tests:
    jobs:
      - angular-test
jobs:
  setup:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - npm install -g  @angular/cli
  angular-test:
    executor:
      name: node/default
      tag: '13.14'
    
    steps:
      - checkout
      - run:
          command: cd ./angular-nini  && npm run test
